apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-node
  labels:
    name: hello-node
    app: hello-node
spec:
  replicas: 1
  selector:
    name: hello-node
  template:
    metadata:
      labels:
        name: hello-node
    spec:
      containers:
      - name: worker
        image: gcr.io/fukudak-playground/hello-node:v2
        ports:
        - containerPort: 8080
