apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-node
  labels:
    name: hello-node
    app: hello-node
spec:
  replicas: 1
  selector:
    name: hello-node
  template:
    metadata:
      labels:
        name: hello-node
    spec:
      containers:
      - name: worker
        image: gcr.io/fukudak-playground/hello-node
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access an environment variable to find the master
          # service's host, comment out the 'value: dns' line above, and
          # uncomment the line below.
          # value: env
        ports:
        - containerPort: 8080
